name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  tests:
    uses: zenstruck/.github/.github/workflows/php-test.yml@main

  code-coverage:
    uses: zenstruck/.github/.github/workflows/php-coverage-codecov.yml@main

  composer-validate:
    uses: zenstruck/.github/.github/workflows/php-composer-validate.yml@main

  sca:
    uses: zenstruck/.github/.github/workflows/php-stan.yml@main

  fixcs:
    name: Run php-cs-fixer and commit any fixes
    needs: [tests, code-coverage, composer-validate, sca]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: php-cs-fixer:3

      - name: Check CS
        run: php-cs-fixer fix --diff --verbose

      - name: Commit files fixed with php-cs-fixer
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          branch: "${{ github.head_ref }}"
          commit_message: "bot: fix cs [skip ci]"
