name: Maintenance

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  sync-with-template:
    name: Sync meta files
    runs-on: ubuntu-latest
    steps:
      - uses: zenstruck/.github@sync-with-template
        with:
          key: ${{ secrets.GPG_PRIVATE_KEY }}

  fixcs:
    name: Run php-cs-fixer
    needs: sync-with-template
    runs-on: ubuntu-latest
    steps:
      - uses: zenstruck/.github@php-cs-fixer
        with:
          php: 8
          key: ${{ secrets.GPG_PRIVATE_KEY }}
